USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS CICD;
CREATE SCHEMA IF NOT EXISTS CICD.ETL;

CREATE OR REPLACE TABLE CICD.ETL.RAW_DATA (
    ID INT AUTOINCREMENT,
    DATA_VALUE VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED BOOLEAN DEFAULT FALSE
);

CREATE OR REPLACE TABLE CICD.ETL.TRANSFORMED_DATA (
    ID INT,
    DATA_VALUE VARCHAR(255),
    TRANSFORMED_VALUE VARCHAR(255),
    PROCESSED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE CICD.ETL.AGGREGATED_DATA (
    REPORT_DATE DATE,
    RECORD_COUNT INT,
    LAST_UPDATED TIMESTAMP_NTZ
);

INSERT INTO CICD.ETL.RAW_DATA (DATA_VALUE) VALUES 
    ('sample_data_1'),
    ('sample_data_2'),
    ('sample_data_3');
