USE ROLE SYSADMIN;
USE DATABASE CICD;
USE SCHEMA ETL;

CREATE OR REPLACE TASK ETL.TASK_EXTRACT_TRANSFORM
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
    CALL ETL.EXTRACT_AND_TRANSFORM();

CREATE OR REPLACE TASK ETL.TASK_AGGREGATE
    WAREHOUSE = COMPUTE_WH
    AFTER ETL.TASK_EXTRACT_TRANSFORM
AS
    CALL ETL.AGGREGATE_DATA();

ALTER TASK ETL.TASK_AGGREGATE RESUME;
ALTER TASK ETL.TASK_EXTRACT_TRANSFORM RESUME;
